[phases.setup]
nixPkgs = [
    "python39",
    "gcc",
    "libffi",
    "portaudio",
    "pkg-config",
    "alsa-lib"
]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn fitcheck.app:app"