services:
  - type: web
    name: fitcheck-ai-stylist
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.9
      - key: SECRET_KEY
        generateValue: true