services:
  - type: web
    name: fitcheck
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: PINTEREST_ACCESS_TOKEN
        sync: false
      - key: PINTEREST_APP_ID
        sync: false
    autoDeploy: false